apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nydus.fullname" . }}-configmap
data:
  DEBUG: "{{ .Values.nydus.debug }}"
  NYDUS_HTTP_PORT: "{{ .Values.nydus.http.port }}"
  SUBSCRIBE_PUBSUB_NAME: "{{ .Values.nydus.subscribe.pubsub.name }}"
  SUBSCRIBE_TOPIC_NAME: "{{ .Values.nydus.subscribe.topic.name }}"
  TARGET_VERSION: "{{ .Values.nydus.target.version }}"
  TARGET_ROOT: "{{ .Values.nydus.target.root }}"
  PUBLISH_PUBSUB_NAME: "{{ .Values.nydus.publish.pubsub.name }}"
  PUBLISH_PUBSUB_TTL: "{{ .Values.nydus.publish.pubsub.ttl.seconds }}"
  INVOKE_TIMEOUT: "{{ .Values.nydus.timeout.invoke.seconds }}"
  PUBLISH_TIMEOUT: "{{ .Values.nydus.timeout.publish.seconds }}"
  CALLBACK_TIMEOUT: "{{ .Values.nydus.timeout.callback.seconds }}"