apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: messagebus
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password
  - name: redisHost
    value: "redis-master.default.svc.cluster.local:6379"
  - name: enableTLS
    value: "false"