apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nydus.fullname" . }}-configmap
data:
  DEBUG: "{{ .Values.nydus.debug }}"
  NYDUS_HTTP_PORT: "{{ .Values.nydus.http.port }}"
  SUBSCRIBE_PUBSUB_NAME: "{{ .Values.nydus.subscribe.pubsub.name }}"
  SUBSCRIBE_TOPIC_NAME: "{{ .Values.nydus.subscribe.topic.name }}"
  TARGET_VERSION: "{{ .Values.nydus.target.version }}"
  TARGET_ROOT: "{{ .Values.nydus.target.root }}"
  PUBLISH_PUBSUB_NAME: "{{ .Values.nydus.publish.pubsub.name }}"
  PUBLISH_PUBSUB_TTL: "{{ .Values.nydus.publish.pubsub.ttl.seconds }}"
  INVOKE_TIMEOUT: "{{ .Values.nydus.timeout.invoke.seconds }}"
  PUBLISH_TIMEOUT: "{{ .Values.nydus.timeout.publish.seconds }}"
  CALLBACK_TIMEOUT: "{{ .Values.nydus.timeout.callback.seconds }}"
  DAPR_HEALTHZ_ADDR: "{{ .Values.nydus.dapr.healthz.address }}"
  DAPR_HEALTHZ_TIMEOUT: "{{ .Values.nydus.dapr.healthz.timeout.seconds }}"
  CLIENT_MAX_CONNS_PER_HOST: "{{ .Values.nydus.client.maxConnsPerHost }}"
  CLIENT_READ_TIMEOUT: "{{ .Values.nydus.client.timeout.read.seconds }}"
  CLIENT_WRITE_TIMEOUT: "{{ .Values.nydus.client.timeout.write.seconds }}"
  CLIENT_HEADER_NORMALIZING: "{{ .Values.nydus.client.headerNormalizing }}"
  SERVER_READ_TIMEOUT: "{{ .Values.nydus.server.timeout.read.seconds }}"
  SERVER_WRITE_TIMEOUT: "{{ .Values.nydus.server.timeout.write.seconds }}"
  SERVER_IDLE_TIMEOUT: "{{ .Values.nydus.server.timeout.idle.seconds }}"
  SERVER_HEADER_NORMALIZING: "{{ .Values.nydus.server.headerNormalizing }}"
  DEFAULT_TO_STRING: "{{ .Values.nydus.print.default.tostring }}"
  XML_TO_STRING: "{{ .Values.nydus.print.xml.tostring }}"
