apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nydus.fullname" . }}
  labels:
    {{- include "nydus.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nydus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        dapr.io/log-as-json: "true"
        dapr.io/enabled: "true"
        dapr.io/log-level: "{{ .Values.dapr.logLevel }}"
        dapr.io/app-id: "{{ include "nydus.fullname" . }}"
        dapr.io/app-port: "{{ .Values.nydus.http.port }}"
        dapr.io/config: "{{ .Values.dapr.config }}"
        dapr.io/sidecar-cpu-limit: 300m
        dapr.io/sidecar-memory-limit: 1000Mi
        dapr.io/sidecar-cpu-request: 100m
        dapr.io/sidecar-memory-request: 250Mi
        dapr.io/http-max-request-size: "10"
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nydus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "nydus.fullname" . }}-configmap
          env:
          - name: NYDUS_HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - name: http
              containerPort: {{ .Values.nydus.http.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
